

import ClientMain from "../components/ClientMain";

// --- SERVER COMPONENT ---
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import MidnightContainer from "@/components/MidnightContainer";
import MidnightSidebar from "@/components/MidnightSidebar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-navy min-h-screen`}
      >
        <MidnightContainer>
          <MidnightSidebar />
          <ClientMain>{children}</ClientMain>
        </MidnightContainer>
      </body>
    </html>
  );
}
